# Problem statement 
## Multiples of 3 or 5 : Problem 1
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [1]:
N = 1000
sum=0
for i in range(1,N):
    if i%3==0 or i%5==0:
        sum = sum + i
print (sum)

233168

## Even Fibonacci numbers : problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [2]:
N = 4000000
#N = 90
F_seq = [1,2]
sum = 2
while F_seq[-1] < N:
    F_seq.append(F_seq[-1] + F_seq[-2])
    if F_seq[-1]%2 == 0 and (F_seq[-1]<N) :
        sum = sum+F_seq[-1]
print (sum)

4613732

## Largest prime factor : problem 3

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [5]:
print ('The prime factors of 13195 are 5, 7, 13 and 29. = ',5*7*13*29)

The prime factors of 13195 are 5, 7, 13 and 29. =  13195

In [66]:
import math
list1 = [1, 2, 3]
list2 = [3, 2, 4]
 
 
result1 = math.prod(list1)
result2 = math.prod(list2)

In [110]:
N=600851475143
N_back = N
pr=2



def is_prime(n):
    for i in range(2,int(math.sqrt(n))+1):
        if n%i==0:
            return False
    return True

def next_prime(n):
    while True:
        n = n+1
        if is_prime(n):
            return n
        
ll = []
while not (math.prod(ll) == (N_back)):
    while N%pr==0:
        print ('dividing prime = ',pr)
        ll.append(pr)
        N = N/pr
    pr = next_prime(pr)
ll

dividing prime =  71
dividing prime =  839
dividing prime =  1471
dividing prime =  6857

[71, 839, 1471, 6857]

In [7]:
71*839*1471*6857 == 600851475143

True

## Largest palindrome product : problem 4

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 Ã— 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [29]:
def is_palindrome(n):
    s = str(n)
    s_len = len(s)
    for i in range(int(s_len/2)):
        if s[i] != s[-(i+1)]:            
            return False
    #print ('palindrome',n)
    return True

In [34]:
l1 =[]
l2 = []
l3 = []
K1 = 800
K2 = 999
for i in range(K2,K1,-1):
    for j in range(K2,K1,-1):
        prd = i*j
        dec = is_palindrome(prd)
        if dec:
            l1.append((i,j,i*j))
            l2.append(prd)
            break

In [35]:
l1

[(993, 913, 906609),
 (982, 869, 853358),
 (968, 916, 886688),
 (966, 858, 828828),
 (962, 924, 888888),
 (959, 803, 770077),
 (957, 894, 855558),
 (946, 888, 840048),
 (932, 924, 861168),
 (924, 962, 888888),
 (921, 847, 780087),
 (916, 968, 886688),
 (914, 902, 824428),
 (913, 993, 906609),
 (909, 902, 819918),
 (902, 914, 824428),
 (897, 924, 828828),
 (894, 957, 855558),
 (888, 946, 840048),
 (871, 847, 737737),
 (869, 982, 853358),
 (868, 946, 821128),
 (867, 924, 801108),
 (863, 869, 749947),
 (858, 966, 828828),
 (848, 946, 802208),
 (847, 921, 780087),
 (844, 957, 807708),
 (836, 836, 698896),
 (834, 814, 678876),
 (831, 968, 804408),
 (822, 803, 660066),
 (819, 913, 747747),
 (814, 834, 678876),
 (812, 858, 696696),
 (804, 814, 654456),
 (803, 959, 770077)]

In [36]:
l2.sort()

In [37]:
l2[-1]

906609

### Copied : more efficient solution - S Anand

In [89]:
n = 0
for a in range(999, 100, -1):
    for b in range(a, 100, -1):
        x = a * b
        if x > n:
            s = str(a * b)
            if s == s[::-1]:
                n = a * b

print (n)

906609

In [ ]:
def is_palindrome(n):
    s = str(n)
    s_len = len(s)
    for i in range(int(s_len/2)):
        if s[i] != s[-(i+1)]:            
            return False
    #print ('palindrome',n)
    return True

## Smallest multiple : Problem 5

2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [40]:
import math

In [41]:
def is_prime(n):
    for i in range(2,int(math.sqrt(n))+1):
        if n%i==0:
            return False
    return True

def next_prime(n):
    while True:
        n = n+1
        if is_prime(n):
            return n

In [60]:
TEST_NUM = 20
t=1
all_primes_l = []
while t<TEST_NUM:
    print (t)
    t=next_prime(t)
    all_primes_l.append(t)

all_primes_l

1
2
3
5
7
11
13
17
19

[2, 3, 5, 7, 11, 13, 17, 19, 23]

In [52]:
prd = 1
for i in all_primes_l:
    prd = prd*i
print (prd)

9699690

In [54]:
9699690/9

1077743.3333333333

# Sum Square Difference : Problem 6


The sum of the squares of the first ten natural numbers is,

1^2 + 2^2 + .... + 10^2 = 385


The square of the sum of the first ten natural numbers is,

(1+2+...+10)^2 = (55)^2 = 3025

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is .

3025 - 385 = 2640

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [7]:

n = 100 
# sum of square of first n natural numbers : 
sum_sq_n = (n * (n+1) * ((2*n)+1)) / 6

# sum of first n numbers 
sum_n = (n * (n+1))/2 
sum_n_sq = sum_n*sum_n


print (int(sum_n_sq - sum_sq_n))

25164150

3025.0